import * as THREE from "three";
const ui=document.querySelector("#ui"),game=document.querySelector("#game");
const state={character:"fawaz",mode:"solo",score:0,stars:0,index:0,streak:0,questions:[],paused:false};
const chars={fawaz:{emoji:"🧑🏻",name:"فواز"},ziyad:{emoji:"🧑🏽",name:"زياد"}};
const questions=[["أ","أسد",["أسد","باب","جمل","نخل"]],["ب","باب",["باب","جمل","نخل","قمر"]],["ت","تفاح",["تفاح","جمل","نخل","قمر"]],["ث","ثعلب",["ثعلب","باب","ورد","جمل"]],["ج","جمل",["جمل","نخل","قمر","باب"]],["ح","حصان",["حصان","تمر","باب","نجم"]],["خ","خيمة",["خيمة","جمل","نخل","قمر"]],["د","دب",["دب","باب","شمس","نخل"]],["ذ","ذهب",["ذهب","جمل","قمر","تمر"]],["ر","رمان",["رمان","نخل","باب","جمل"]]];
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9bdcff);scene.fog=new THREE.Fog(0x9bdcff,28,90);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,150);camera.position.set(0,7,15);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;game.appendChild(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xfff2cf,0x8a6b4b,2.2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffe7ad,3);sun.position.set(-12,18,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const world=new THREE.Group();scene.add(world);
const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.9});
function mesh(g,m,p){const x=new THREE.Mesh(g,m);x.position.copy(p);x.castShadow=x.receiveShadow=true;world.add(x);return x}
mesh(new THREE.PlaneGeometry(100,100),mat(0xe7c27b),new THREE.Vector3(0,-.05,0)).rotation.x=-Math.PI/2;
for(let i=0;i<16;i++){const x=(Math.random()-.5)*65,z=-Math.random()*60-5,s=.7+Math.random()*1.7;mesh(new THREE.SphereGeometry(s,12,8),mat(i%2?0xe1b96f:0xf0cf8a),new THREE.Vector3(x,s*.35,z)).scale.y=.45}
function palm(x,z){const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.22,.34,3.4,8),mat(0x79502f));trunk.position.y=1.7;g.add(trunk);for(let i=0;i<7;i++){const leaf=new THREE.Mesh(new THREE.ConeGeometry(.28,2.6,5),mat(0x47784a));leaf.position.y=3.5;leaf.rotation.z=Math.PI/2;leaf.rotation.y=i*Math.PI*2/7;g.add(leaf)}g.position.set(x,0,z);world.add(g);return g}
palm(-8,-12);palm(9,-20);palm(-15,-31);palm(13,-39);
const oasis=new THREE.Mesh(new THREE.CylinderGeometry(4.5,4.8,.12,48),new THREE.MeshStandardMaterial({color:0x55b9d5,roughness:.3,metalness:.05}));oasis.position.set(8,.08,-34);oasis.receiveShadow=true;world.add(oasis);
function camel(){const g=new THREE.Group(),brown=mat(0xb8793f);const body=new THREE.Mesh(new THREE.SphereGeometry(1.5,16,12),brown);body.scale.set(1.5,.85,.75);body.position.y=1.35;g.add(body);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.45,.62,2.3,12),brown);neck.position.set(.9,2.35,0);neck.rotation.z=-.35;g.add(neck);const head=new THREE.Mesh(new THREE.SphereGeometry(.62,12,10),brown);head.position.set(1.25,3.25,0);g.add(head);for(const z of[-.5,.5]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.18,.22,1.4,8),brown);leg.position.set(-.75,z,0);g.add(leg)}g.position.set(-1,0,-8);world.add(g);return g}const camelObj=camel();
const player=new THREE.Group();const robe=mat(0x5f7f69),skin=mat(0xc98d64);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.48,1.15,6,12),robe);body.position.y=1.05;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.43,16,12),skin);head.position.y=2.05;player.add(head);const scarf=new THREE.Mesh(new THREE.TorusGeometry(.45,.08,8,16),mat(0xf3e2bb));scarf.rotation.x=Math.PI/2;scarf.position.y=1.82;player.add(scarf);player.position.set(0,0,5);scene.add(player);
function skyDecor(){const sunG=new THREE.Mesh(new THREE.SphereGeometry(2.2,20,16),new THREE.MeshBasicMaterial({color:0xffd86e}));sunG.position.set(-22,19,-45);scene.add(sunG)}skyDecor();
function hud(){document.querySelector("#hud")?.remove();const h=document.createElement("div");h.id="hud";h.className="hud";h.innerHTML='<div class="pill">⭐ <span id="score">0</span></div><b class="pill">'+chars[state.character].emoji+" "+chars[state.character].name+'</b><button id="pause">Ⅱ</button>';ui.append(h);const p=document.createElement("div");p.className="progress";p.innerHTML="<i></i>";ui.append(p);document.querySelector("#pause").onclick=pause}
function question(){document.querySelector("#question")?.remove();const q=state.questions[state.index],p=document.createElement("div");p.id="question";p.className="panel";p.innerHTML='<h2>اختر الكلمة التي تبدأ بحرف «'+q[0]+'»</h2><p class="sub">سؤال '+(state.index+1)+' / '+state.questions.length+'</p><div class="answers">'+q[2].map(x=>'<button class="answer">'+x+"</button>").join("")+'</div><div class="feedback"></div>';ui.append(p);p.querySelectorAll(".answer").forEach(b=>b.onclick=()=>answer(b,q));document.querySelector(".progress i").style.width=state.index/state.questions.length*100+"%"}
function answer(btn,q){const all=document.querySelectorAll(".answer");all.forEach(x=>x.disabled=true);const ok=btn.textContent===q[1];btn.classList.add(ok?"correct":"wrong");if(ok){state.streak++;state.score+=10+Math.min(10,state.streak*2);if(state.streak%3===0)state.stars++}else{state.streak=0;all.forEach(x=>{if(x.textContent===q[1])x.classList.add("correct")})}document.querySelector("#score").textContent=state.score;document.querySelector(".feedback").textContent=ok?"ممتاز! ⭐":"قريب جدًا! الإجابة الصحيحة: "+q[1];setTimeout(()=>{state.index++;if(state.index<state.questions.length)question();else finish()},800)}
function pause(){if(document.querySelector(".menu"))return;state.paused=true;const m=document.createElement("div");m.className="menu";m.innerHTML='<div class="sheet"><h1>توقف مؤقت 🌿</h1><p>خذ نفسًا ثم أكمل رحلتك.</p><button class="start" id="resume">متابعة</button><button class="start" id="home">الرئيسية</button></div>';ui.append(m);m.querySelector("#resume").onclick=()=>{state.paused=false;m.remove()};m.querySelector("#home").onclick=()=>{m.remove();home()}}
function finish(){localStorage.setItem("badia-score",String((+localStorage.getItem("badia-score")||0)+state.score));ui.innerHTML='<div class="menu"><div class="sheet result"><div class="big">🏆⭐</div><h1>أحسنت يا '+chars[state.character].name+'!</h1><p>أنهيت مغامرة الحروف.</p><h2>'+state.score+" نقطة</h2><p>"+state.stars+' نجوم مكتسبة ⭐</p><button class="start" id="again">رحلة جديدة</button><button class="start" id="home">الرئيسية</button></div></div>';document.querySelector("#again").onclick=start;document.querySelector("#home").onclick=home}
function home(){ui.innerHTML='<div class="menu"><div class="sheet"><h1>بادية الحروف 🐪</h1><p>مغامرة عربية ثلاثية الأبعاد</p><h3>اختر شخصيتك</h3><div class="choice">'+Object.entries(chars).map(([k,c])=>'<button class="'+(state.character===k?"active":"")+'" data-c="'+k+'"><b>'+c.emoji+" "+c.name+'</b><span>مغامر في الصحراء</span></button>').join("")+'</div><h3>طريقة اللعب</h3><div class="choice"><button class="'+(state.mode==="solo"?"active":"")+'" data-m="solo"><b>🏜️ مغامرة فردية</b><span>تحديات الحروف</span></button><button class="'+(state.mode==="duo"?"active":"")+'" data-m="duo"><b>👥 فواز + زياد</b><span>نظام تنافسي قريبًا</span></button></div><button class="start" id="start">ابدأ الرحلة ←</button></div></div>';ui.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{state.character=b.dataset.c;home()});ui.querySelectorAll("[data-m]").forEach(b=>b.onclick=()=>{state.mode=b.dataset.m;home()});ui.querySelector("#start").onclick=start}
function start(){state.score=0;state.stars=0;state.index=0;state.streak=0;state.questions=[...questions].sort(()=>Math.random()-.5);ui.innerHTML="";hud();question()}
let keys={};addEventListener("keydown",e=>keys[e.key.toLowerCase()]=true);addEventListener("keyup",e=>keys[e.key.toLowerCase()]=false);
addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7))});
let last=performance.now();function loop(t){const dt=Math.min((t-last)/1000,.05);last=t;if(!state.paused&&state.index>=0&&state.questions.length){const speed=5*dt;if(keys.w||keys.arrowup)player.position.z-=speed;if(keys.s||keys.arrowdown)player.position.z+=speed;if(keys.a||keys.arrowleft)player.position.x-=speed;if(keys.d||keys.arrowright)player.position.x+=speed;player.position.x=THREE.MathUtils.clamp(player.position.x,-12,12);player.position.z=THREE.MathUtils.clamp(player.position.z,-42,8)}camelObj.rotation.y=Math.sin(t*.0004)*.05;player.position.y=Math.sin(t*.002)*.025;camera.lookAt(player.position.x*.18,1,-12);renderer.render(scene,camera);requestAnimationFrame(loop)}home();requestAnimationFrame(loop);